# Generated by Django 5.0.6 on 2024-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(choices=[(False, 'pending'), (True, 'completed')], default=False),
        ),
    ]
