# Generated by Django 5.0.6 on 2024-06-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_event_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='partecipants',
            new_name='participants',
        ),
    ]
