# Generated by Django 5.0.6 on 2024-06-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_project_description_user_role_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=5),
        ),
    ]
